### ISSUE TITLE
add Windows-1252 encoding

### ISSUE THREAD

**Issue by henrydatei** [AxelTerizaki/ultrastar2ass#10]
Can you add support for the Windows-1252 encoding?

I've attached you a file, opening it with UTF-8 doesn't work this chracter: `’` (no idea why the author of the file used this instead of `'`)

[Britney Spears - Criminal.txt](https://github.com/user-attachments/files/17736003/Britney.Spears.-.Criminal.txt)

**Comment by henrydatei** [comment]
Hm, that didn't fix the issue. When I run
```
ultrastar2ass Britney\ Spears\ -\ Criminal.txt --encoding=windows-1252
```
I get
```

**Comment by henrydatei** [comment]
With further reading it seems to be that node does not support a lot of encodings: https://stackoverflow.com/questions/14551608/list-of-encodings-that-node-js-supports, especially not Windows-1252.

**Comment by AxelTerizaki** [comment]
Indeed, you might have to convert it yourself first using iconv I'm afraid.
