### ISSUE TITLE
ASS 2 Ultrastar ?

### ISSUE THREAD

**Issue by EL-R1** [AxelTerizaki/ultrastar2ass#5]
Is the opposite possible ?
Or is there already something to translate ass file into ultralstar txt ?

**Comment by AxelTerizaki** [comment]
Hello.

You would get a working karaoke but without any pitch notes to play with via Ultrastar.

You might want to take a look at [KaraLuxer](https://github.com/WarwickAnimeSoc/KaraLuxer) which takes Karaoke Mugen's ASS files and turns them into compatible Vocaluxe songs (which is a Ultrastar clone if I'm not mistaken.

**Comment by EL-R1** [comment]
Oh, i tried it and unfortunatly it doesn't work for UltraStar, like the folder is not recognized.
But for Vocaluxe it works perfectly.
I don't know why

**Comment by AxelTerizaki** [comment]
Sadly I can't help more than that, it's a script to turn ultrastar lyrics into ASS, nothing more :)
